source/config/urls.py
# djauth/urls.py
from . import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import ajax_call
from msg import ajax_call as msg_ajax_call
from django.conf.urls import url


urlpatterns = [
    path('chapeau/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('agenda/', include('agenda.urls'), name='agenda'),
    path('accueil/', include('info.urls'), name='info'),
    path('odk/', include('odk.urls'), name='odk'),
    # path('culture/', include('cult.urls'), name='cult'),
    url(r'^filer/', include('filer.urls')),
    path('', include('cms.urls'), name='cpcms'), # HBP attention BASE_URL du CMS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns + [
    path('ajax/ddl_zip', ajax_call.ddl_zip, name='ajax_ddl_zip'),
    path('ajax/ddl_contact', ajax_call.ddl_contact, name='ajax_ddl_contact'),
    path('ajax/inscription/upd', ajax_call.inscription_update, name='inscription_update'),
    path('ajax/inscription_block/create', ajax_call.inscription_block_create, name='inscription_block_create'),
    path('ajax/msgdet/del', msg_ajax_call.msgdet_delete, name='msgdet_delete'),
]


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

source/msg/urls.py
# -*- coding: utf-8 -*-
"""
msg.urls description

.. todo:: ajouter la navigation dans les centres pilotes
.. todo:: ajouter la navigation dans les cultures
"""
# from django.conf.urls import url
from django.urls import path
from django.conf import settings

from . import views

__author__ = "jph"
__email__ = "jph@openjph.be"
__copyright__ = "Copyright 2016, Jean Pierre Huart"
__license__ = "GPLv3"
__date__ = "2016-12-01"
__version__ = "1.1"
__status__ = "Development"

app_name = "msg"
# pour pouvoir utiliser msg:rech_mult dans les url

urlpatterns = [
    path("", views.MsgListView.as_view(), name="msg_list"),
    # path("oleagineux?listeenvoi=15", views.MsgListView.as_view(), name="msg_list_oleo"),
    path("rechmult/", views.MsgListView.as_view(), name="rechmult"),
    path("new/", views.msg_new, name="new"),
    path("<pk>", views.MsgDetailView.as_view(), name="msg_consult"),
    path("<pk>/envoyer_confirm/", views.MsgDetailView.as_view(), name="envoyer_confirm"),
    path("<pk>/publier_confirm/", views.MsgDetailView.as_view(), name="publier_confirm"),
    path("<pk>/copier_confirm/", views.MsgDetailView.as_view(), name="copier_confirm"),
    path("<pk>/del_confirm/", views.MsgDetailView.as_view(), name="supprimer_confirm"),
    path("<msg_id>/envoyer/", views.msg_envoyer, name="envoyerok"),
    path("<msg_id>/publier/", views.msg_publier, name="publierok"),
    path("<msg_id>/copier/", views.msg_copier, name="copierok"),
    path("<msg_id>/del/", views.msg_delete, name="supprimerok"),
    path("<msg_id>/upd/", views.msg_update, name="msg_upd"),
    path("<msg_id>/preview/", views.preview_email, name="preview_email"),
    # path("<pk>/del/", views.MsgDeleteView.as_view(), name="supprimer"),
    path("<msg_id>/<msgdet_id>/viewdetail/", views.msgdet_consult, name="msgdet_consult"),
]

source/agenda/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from accounts.models import CentrePilote, GeoZip, ModeDeProduction, Profession
from info.models import WebLink


class Event(models.Model):
    EVENT_TYPE = (
        ("event", "Événement"),
        ("train", "Formation"),
        ("visit", "Visite"),
    )    
    centrepilote = models.ForeignKey(
        CentrePilote,
        on_delete=models.PROTECT,
        verbose_name=_("Centre Pilote")
    )  
    title = models.CharField(_("Titre"), max_length=255)
    short_desc = RichTextField(_("Descriptif"), blank=True, null=True)
    event_type = models.CharField(
        _("Type d'événement"),
        max_length=5,
        choices=EVENT_TYPE,
        default="visit"
    )    
    culture_txt = models.CharField(_("Cultures"), max_length=500,
        help_text=_("Liste des cultures séparé par une virgule")
        )
    modeprod = models.ManyToManyField(
        ModeDeProduction, verbose_name=_("Type d'essais"),
        help_text=_("Maintenir la touche 'Ctrl' enfoncée pour sélectionner plusieurs essais")
    )
    visio_link = models.URLField(_("Visio link"), blank=True, null=True,
        help_text=_("URL de la visio si nécessaire")
    )
    public_cible = models.ForeignKey(
        Profession, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('Public cible'),
        help_text=_("Ne rien préciser si tout public")    
    )
    begin_date = models.DateField(_("Date"))
    begin_time = models.TimeField(_("Heure début"))
    end_date = models.DateField(_("Date fin"), blank=True, null=True)
    end_time = models.TimeField(_("Heure fin"), blank=True, null=True)
    street = models.CharField(_("Rue + Nr"), max_length=255, blank=True, null=True, help_text=_("Nom de rue, numéro"))
    # ziploc = models.ForeignKey(GeoZip, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_("Code postal"))
    codepostal = models.CharField(_('Code postal'), max_length=255, blank=True, null=True, help_text=_('CP et localisation'))
    place = models.CharField(_("Lieu dit/Ferme"), max_length=255, blank=True, null=True)
    organisation = models.ManyToManyField(WebLink, verbose_name="Organisé par", blank=True,
        help_text=_("Maintenir la touche 'Ctrl' enfoncée pour sélectionner plusieurs organisateurs")
    )

    class Meta:
        verbose_name = _("Agenda")
        ordering = ["begin_date", "begin_time"]
    
    def beginend_time(self):
        # begin_date = self.begin_date.strftime('%A %d %B %Y')
        begin_time = self.begin_time.strftime('%H:%M')
        if self.end_time:
            end_time = self.end_time.strftime('%H:%M')
            return f'<span class="time-display">{begin_time}</span><span class="m-2">&raquo;</span><span class="time-display">{end_time}</span>'
        else:
            return f'<span class="time-display">{begin_time}</span>'

    @property
    def get_public_cible(self):
        if self.public_cible is None:
            return "Tout public"
        else:
            return self.public_cible.description

    @property
    def get_modeprod_list(self):
        retstr = ", ".join([a.nom for a in self.modeprod.all()])
        return retstr.strip()

    @property
    def get_organisation_list(self):
        retstr = " ".join([a.get_logo() for a in self.organisation.all()])
        return retstr.strip()

    @property
    def get_organisation_list_large(self):
        retstr = " ".join([a.get_logo_large() for a in self.organisation.all()])
        return retstr.strip()

    def get_absolute_url(self):
        return reverse('agenda:event_detail', args=[str(self.id)])

    def get_title(self):
        begin_date = self.begin_date.strftime('%d/%m/%Y')
        begin_time = self.begin_time.strftime('%H:%M')
        return "{0} » {1} {2} - {3}".format(self._meta.verbose_name, self.title, begin_date, begin_time)

    def __str__(self):
        return self.title

source/msg/models.py
# -*- coding: utf-8 -*-
"""
msg.models description
"""
from ckeditor.fields import RichTextField
from filer.fields.image import FilerImageField

from django.utils import timezone
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django.urls import reverse
# from cms.admin.placeholderadmin import PlaceholderAdminMixin

from cms.models.fields import PlaceholderField
from accounts.models import ListeEnvoi, CentrePilote
# from cult.models import Culture, Ram

__author__ = "openHBP"
__email__ = "p.houben@cra.wallonie.be"
__copyright__ = "Copyright 2020, Patrick Houben"
__license__ = "GPLv3"
__date__ = "2020-10-13"
__version__ = "1.0.3"
__statut__ = "Development"


# Keep for migration history reason (presence in initial_0001)
class MyPlaceholderField(PlaceholderField):
    pass

class Categorie(models.Model):
    """
    Catégories de message
    event: Evénement
    comm: Communication
    avert: Avertissement
    """
    code = models.CharField(max_length=5, default="avert")
    nom = models.CharField(max_length=15, default="avertissement")
    icone = models.CharField(max_length=30, blank=True, null=True)
    couleur = models.CharField(max_length=7, blank=True, null=True)

    class Meta:
        app_label = "msg"
        ordering = ["nom"]

    def __str__(self):
        return "{0}".format(self.nom)


class Msg(models.Model):
    """
    Message à envoyer aux abonnés
    """
    MSG_STATUTS = (
        ("draft", _("Brouillon")),
        ("publie", _("Publié")),
        ("envoye", _("Envoyé")),
        # ("archive", _("archivé")),
    )

    centrepilote = models.ForeignKey(CentrePilote, on_delete=models.CASCADE)
    msg_created = models.DateTimeField(_("Créé le"), default=timezone.now)
    msg_date = models.DateTimeField(_("Envoyé le"), default=timezone.now)
    title = models.CharField(_("Sujet de l'E-mail"), max_length=255,
        help_text = "Le sujet est toujours précédé de 3 items: nom centre pilote - nom liste d'envoi - date d'envoi. Il est donc inutile de les ajouter au sujet.")
    listeenvoi = models.ForeignKey(ListeEnvoi, on_delete=models.CASCADE, verbose_name=_("Liste d'envoi"))
    summary_img = FilerImageField(
        related_name="summary_img", on_delete=models.PROTECT, 
        null=True, blank=True, verbose_name=_("Image d'accroche"),
        help_text=_("Sans image, le logo du centre pilote sera affiché.")
        )
    summary_txt = RichTextField(_("Bref résumé"),
        blank=True, null=True,
        help_text=_("Sans résumé, les différents sous-titres du message seront affichés.")
        )
    # RichTextField(_("Détail"), blank=True, null=True)
    statut = models.CharField(
        _("Statut"),
        max_length=10,
        choices=MSG_STATUTS,
        default="draft",
        help_text=_("Remettre en publié pour pouvoir réenvoyer l'avertissement."),
    )
    msg_nextdate = models.DateField(_("Date du prochain avis"), blank=True, null=True,
        help_text=_("Ne rien saisir pour afficher 'Dernier avis de la saison' dans l'email d'avertissement."))
    display_nextdate = models.BooleanField(_("Afficher la date du prochain avis"), default=False,
        help_text=_("Cochez cette case pour afficher la date prévue du prochain avis dans l'email d'avertissement."))

    class Meta:
        app_label = "msg"
        verbose_name = _("Avertissement")
        #ordering = ["-id"] # pour que ça fonctionne avec prev et next btn
        ordering = ["-msg_date"]

    def get_msg_date(self):
        if self.msg_date is None:
            msg_date = self.msg_created.strftime('%d.%m.%Y')
        else:
            msg_date = self.msg_date.strftime('%d.%m.%Y')
        return msg_date

    def get_title_stamp_ext(self):
        if self.id > 156:
            return self.get_title()
        else:
            return self.title

    def get_statut(self):
        """
        Return statut text
        """
        statut_title = self.get_statut_display().capitalize()
        if self.msg_date is not None:
            statut_date = self.msg_date.strftime('%d.%m.%Y')
        else:
            statut_date = self.msg_created.strftime('%d.%m.%Y')
        retstr = f"{statut_title} le {statut_date}"
        if self.statut == "draft":
            retstr = f"{statut_title} du {statut_date}"
        return retstr

    def display_placeholder(self):
        """
        Flag pour changement de version en octobre avec msg_id = 164
        return True or False
        """
        if int(self.id) > 163:
            return True
        else:
            return False

    def get_img200(self):
        if self.summary_img is not None:
            options = {'size': (200, 150)}
            summary_img_url = self.summary_img.file.get_thumbnail(options).url
            return summary_img_url
        else:
            return None

    def get_img300(self):
        if self.summary_img is not None:
            options = {'size': (300, 225), 'crop': True}
            summary_img_url = self.summary_img.file.get_thumbnail(options).url
            return summary_img_url
        else:
            return None

    def get_img400(self):
        if self.summary_img is not None:
            # if self.summary_img.width > self.summary_img.height:
            options = {'size': (400, 300), 'crop': True}
            # else:
            #     options = {'size': (300, 400), 'crop': True, 'upscale': True}
            summary_img_url = self.summary_img.file.get_thumbnail(options).url
            return summary_img_url
        else:
            return None

    def get_absolute_url(self):
        return reverse('msg:msg_consult', args=[str(self.id)])

    def get_title(self):
        return f"{self.centrepilote} {self.listeenvoi} {self.get_msg_date()}"

    def __str__(self):
        return self.get_title()

    # def __str__(self):
    #     return "{}".format(self.title)


class MsgDet(models.Model):
    """
    Détail du message
    """
    msg = models.ForeignKey(Msg, on_delete=models.CASCADE, verbose_name=_("Titre"))
    title = models.CharField(_("Sous-titre"), max_length=255)
    short_text2 = PlaceholderField("msgdet_slot")
    short_text = RichTextField(_("Détail"), blank=True, null=True)
    categorie = models.ForeignKey(
        Categorie, on_delete=models.CASCADE, help_text=_("Avertissement/Communication/Événement"),
        verbose_name=_("Categorie")
    )
    # culture = models.ManyToManyField(Culture, blank=True, verbose_name=_("Cultures"))
    # ram = models.ManyToManyField(
    #     Ram, blank=True, verbose_name=_("Ravageurs et maladies"))
    class Meta:
        app_label = "msg"
        verbose_name = _("Détail Avertissement")
        ordering = ["categorie", "title"]

    def get_absolute_url(self):
        return reverse('msg:msgdet_consult', args=[str(self.msg_id), str(self.id)])

    def get_cultures(self):
        return ", ".join(i.nom for i in self.culture.all())

    def get_rams(self):
        return ", ".join(i.nom for i in self.ram.all())

    def get_title(self):
        msg_date = self.msg.get_msg_date()
        return f"Détail Avertissement du {msg_date}"

    def __str__(self):
        return self.get_title()

source/templates/plugin/cp_hosted.html
{% for object in hosted_in %}
<a href="/cp/{{object.code}}/" class="container-box-main header-home">  
    <p class="title-cp"><strong>
        {{object.secteur|capfirst}}
    </strong></p>
    <img id="logo-cp" class="img-fluid img-200" src={{object.logo.url}}?reloadV44 alt={{object.acronyme}}>
</a>
{% endfor %}

source/templates/plugin/cp_list_plugin.html
<h2>3 hébergés sur ce site</h2>
<div class="flex-container">
    {% for object in hosted_in %}
    
        <a href="/cp/{{object.code}}/" class="container-box-main">
        <p class="text-white"><strong>
            {{object.secteur|capfirst}}
        </strong></p>
        <img class="img-fluid" src={{object.logo.url}} alt={{object.acronyme}}>
        </a>
    
    {% endfor %}
</div>

<h2>8 hébergés ailleurs</h2>
<div class="flex-container">
    {% for object in hosted_out %}
    
        <a href="/cp/{{object.code}}/" class="container-box-main">
        <p class="text-white"><strong>
            {{object.secteur|capfirst}}
        </strong></p>
        <img class="img-fluid" src={{object.logo.url}} alt={{object.acronyme}}>
        </a>
    
    {% endfor %}
</div>

source/templates/plugin/cp_location.html
{% load csstags %}

<div class="flex-container">
    {% for cploc in cploc_list %}
    <div class="container-box-warning">
        <h4>{{cploc.intitule}}</h4>
        <p>{{cploc.title}}</p>
        <p><i>{{cploc.subtitle|default_if_none:""}}</i></p>

        <div class="flex-container-start">
            <p class="me-2"><i class="far fa-envelope"></i></p>
            <div class="address">
                <div>
                    <p>{{cploc.street|default_if_none:""}}</p>
                    <p>{{cploc.zip|default_if_none:""}}</p>
                </div>
            </div>
        </div>

        <p><i class="fas fa-at"></i><a href="mailto:{{cploc.contact.email}}">  {{cploc.contact.email}}</a></p>
        {% if cploc.contact.phone %}
            <p><i class="fas fa-phone-alt"></i>  {{cploc.contact.phone}}</p>
        {% endif %}
        {% if cploc.contact.mobile %}
            <p><i class="fas fa-mobile"></i>  {{cploc.contact.mobile}}</p>
        {% endif %}

        {% if user.is_manager %}
        <a style="margin: 10px 0px;" class="btn btn-danger2" href="{% url 'cploc_update' cploc.id %}">Modifier</a>
        {% endif %}     
    </div>
    {% endfor %}
</div>


{% if user.is_manager %}
    <a class="btn btn-success2" href="{% url 'cploc_create' object.id %}">Ajouter  Localisation/Siège d'activité?</a>
{% endif %}

source/templates/plugin/cp_presentation.html
{% load csstags %}

<h4><a href="{{object.siteweb}}" target="_blank">{{ object.acronyme }}</a> {{ object.nom }}</h4>


<img class="img-left img-fluid" src="{{ object.logo.url }}" alt="{{ object.acronyme }}">
<div class="container-text">
    {{ object.short_text|safe }}

    <p><strong>{{ object.secteur|capfirst }}</strong>
        <a href="{{object.siteweb}}" target="_blank">{{object.siteweb|default_if_none:""}}</a>
    </p>

    <p>{{ object.get_social_link|safe }}</p>
</div>



<div class="row">
    <div class="col-md-12">
        {% if user.is_manager %}
            <a class="btn btn-danger2" href="{% url 'cp_update' object.id %}">Modifier</a>
        {% endif %}
    </div>
</div>

source/templates/plugin/cp_presentation_rowcol.html
{% load csstags %}

<div class="row">
    <div class="col-md-12">
        <h3><a href="{{object.siteweb}}" target="_blank">{{ object.acronyme }}</a> {{ object.nom }}</h3>
    </div>
</div>

<div class="row">
    <div class="col-sm-12 col-md-3">
        <img class="img-left img-fluid" src="{{ object.logo.url }}" alt="{{ object.acronyme }}">
    </div>
    <div class="col-sm-12 col-md-9">
        {{ object.short_text|safe }}
    </div>
    <div class="col-sm-12 col-md-12">
        <p><strong>{{ object.secteur|capfirst }}</strong>
        <a href="{{object.siteweb}}" target="_blank">{{object.siteweb|default_if_none:""}}</a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        {% if user.is_manager %}
            <a class="btn btn-danger2" href="{% url 'cp_update' object.id %}">Modifier</a>
        {% endif %}
    </div>
</div>

source/templates/plugin/cp_team.html
{% load csstags %}

<div class="flex-container">
{% for profile in profile_list %}
    <div class="container-box-warning">
        <h2>{{profile.get_full_name}}</h2>
        <p><strong>{{profile.jobdesc|default_if_none:""}}</strong></p>
        <p><i class="fas fa-at"></i><a href="mailto:{{profile.email}}"> {{profile.email}}</a></p>
        {% if profile.phone %}
            <p><i class="fas fa-phone-alt"></i> {{profile.phone}}</p>
        {% endif %}
        {% if profile.mobile %}
        <p><i class="fas fa-mobile"></i> {{profile.mobile}}</p>
        {% endif %}
        <a class="btn btn-danger2" href="{% url 'profile_detail' profile.id %}">Modifier</a>
    </div>
{% endfor %}
</div>

source/templates/plugin/event_list.html
<div id="event-list-home">
{% for object in event_list %}
<hr class="hr-cp">
<div class="flex-container mb-2">
    <a href="{{object.get_absolute_url}}" target="_blank" class="btn btn-main2 m-1">
        {{object.begin_date|date:"d.m.Y"}}
    </a>
    <a href="{{object.get_absolute_url}}" target="_blank" class="m-1">
        {{object.title}}
    </a>
    <span class="m-1">{{object.get_event_type_display|default_if_none:""}}</span>
    <span class="flex-container-start m-1">{{object.beginend_time|safe}}</span>
</div>    
<div>

    {% if object.codepostal %}
        <div class="address">
            <p class="me-2"></p>
            <p><i class="fas fa-map-marker-alt me-2"></i>{{object.street|default_if_none:""}}</br>
            {{object.codepostal|default_if_none:""}}</p>
        </div>
    {% endif %}
    <p>{{object.culture_txt|default_if_none:""}}</p>
    <div class="agenda-org">{{ object.get_organisation_list|safe }}</div> 
</div>

{% endfor %}
</div>

source/templates/plugin/event_list_old.html
<div id="event-list-home">
{% for object in event_list %}
<hr class="hr-cp">
<div class="flex-container-start">
    <div>
        <div class="container-box-day">
            <p class="text-white">{{object.begin_date|date:"l"|capfirst}}</p>
            <p class="calendar-day"><strong>{{object.begin_date|date:"j"}}</strong></p>
            <p class="text-white">{{object.begin_date|date:"F"|upper}}</p>
        </div>
        <h5 class="flex-container-start">{{object.beginend_time|safe}}</h5>
    </div>
    <div>
        <h3 class="mt-2 flex-container-start">
            <a href="{{object.get_absolute_url}}" target="_blank">
                <i class="me-2 fas fa-info-circle"></i>{{object.title}}
            </a>
            &nbsp;&nbsp;
            <span>{{object.get_event_type_display|default_if_none:""}}</span>
        </h3>
        {% if object.codepostal %}
            <div class="address">
                <p class="me-2"></p>
                <p><i class="fas fa-map-marker-alt me-2"></i>{{object.street|default_if_none:""}}</br>
                {{object.codepostal|default_if_none:""}}</p>
            </div>
        {% endif %}
        <p>{{object.culture_txt|default_if_none:""}}</p>
        <div class="agenda-org">{{ object.get_organisation_list|safe }}</div> 
    </div>
</div>
{% endfor %}
</div>

source/templates/plugin/msg_caroussel.html
<div class="carousel" data-flickity='{ "groupCells": true, "imagesLoaded": true}'>
    {% for msg in recent_msgs %}
        <!-- The slideshow -->
        <div class="carousel-cell">
            <img width="400px" class="imgslider" src="{{msg.get_img300}}" alt="{{msg.title}}">
            <a href="{% url 'msg:msg_consult' msg.id %}" class="img-txt-up btn btn-main2">{{ msg.get_title }}</a>
            <a href="{% url 'msg:msg_consult' msg.id %}" class="img-txt-down btn btn-info2">{{ msg.title }}</a>
        </div>
    {% endfor %}
</div>

source/templates/plugin/msg_last.html
{% load csstags %}

<div id="msg-list-home">
{% for object in msg_list %}
    
    <hr class="hr-cp">

    <a href="{% url 'msg:msg_consult' object.id %}" class="btn btn-main2 m-1">
        {{ object.get_title }}
    </a>            

    <div class="flex-container-start grey-box">
        {% if object.summary_img %}
            <img id="summary-img" class="img-left img-fluid img-200" src="{{object.summary_img.url}}" alt="{{object.centrepilote}}">
        {% else %}
            <img id="summary-img" class="img-left img-fluid img-200" src="{{object.centrepilote.logo.url}}" alt="{{object.centrepilote}}">
        {% endif %}

        <div>
            {% if object.summary_txt %}
                <div style="font-size: small">{{ object.summary_txt|safe|truncatewords_html:50 }}</div>
            {% else %}
                {% for i in object.msgdet_set.all %}
                <p class="text-{{ i.categorie.code }}" style="margin-bottom: .5rem; font-size: small;">
                    <i class="fas {{ i.categorie.icone }} me-2"></i>{{ i.title }}
                </p>     
                {% endfor %}
            {% endif %}
        </div>

    </div>
{% endfor %}
</div>