source/config/urls.py
# djauth/urls.py
from . import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import ajax_call
from msg import ajax_call as msg_ajax_call
from django.conf.urls import url


urlpatterns = [
    path('chapeau/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('agenda/', include('agenda.urls'), name='agenda'),
    path('accueil/', include('info.urls'), name='info'),
    path('odk/', include('odk.urls'), name='odk'),
    # path('culture/', include('cult.urls'), name='cult'),
    url(r'^filer/', include('filer.urls')),
    path('', include('cms.urls'), name='cpcms'), # HBP attention BASE_URL du CMS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns + [
    path('ajax/ddl_zip', ajax_call.ddl_zip, name='ajax_ddl_zip'),
    path('ajax/ddl_contact', ajax_call.ddl_contact, name='ajax_ddl_contact'),
    path('ajax/inscription/upd', ajax_call.inscription_update, name='inscription_update'),
    path('ajax/inscription_block/create', ajax_call.inscription_block_create, name='inscription_block_create'),
    path('ajax/msgdet/del', msg_ajax_call.msgdet_delete, name='msgdet_delete'),
]


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

source/info/urls.py
# encoding:utf-8
'''
Created on 13/04/2020
@author: p.houben
'''
from django.urls import path
from .views import (
    WebLinkList, WebLinkDetail, weblink_detail,
    goaccess_list, accueil, goaccess_report, goaccess_report_year
)

app_name = "info"

urlpatterns = [
    path('', accueil, name='accueil'),
    path('autres/', WebLinkList.as_view(menucateg='autre'), name='autre'),
    path('partenaires/', WebLinkList.as_view(menucateg='partenaire'), name='partenaire'),
    path('outils/', WebLinkList.as_view(menucateg='outil'), name='outil'),
    # ne pas changer ci-dessous, c'est une popup avec appel ajax!
    path('detail/', weblink_detail, name='weblink_detail'), 
    path('statistiques/', goaccess_list, name='cpilote_stat'),
    path('statistiques/mensuelle/<month>', goaccess_report, name='goaccess_report'),
    path('statistiques/annuelle/<year>', goaccess_report_year, name='goaccess_report_year'),
]

source/msg/urls.py
# -*- coding: utf-8 -*-
"""
msg.urls description

.. todo:: ajouter la navigation dans les centres pilotes
.. todo:: ajouter la navigation dans les cultures
"""
# from django.conf.urls import url
from django.urls import path
from django.conf import settings

from . import views

__author__ = "jph"
__email__ = "jph@openjph.be"
__copyright__ = "Copyright 2016, Jean Pierre Huart"
__license__ = "GPLv3"
__date__ = "2016-12-01"
__version__ = "1.1"
__status__ = "Development"

app_name = "msg"
# pour pouvoir utiliser msg:rech_mult dans les url

urlpatterns = [
    path("", views.MsgListView.as_view(), name="msg_list"),
    # path("oleagineux?listeenvoi=15", views.MsgListView.as_view(), name="msg_list_oleo"),
    path("rechmult/", views.MsgListView.as_view(), name="rechmult"),
    path("new/", views.msg_new, name="new"),
    path("<pk>", views.MsgDetailView.as_view(), name="msg_consult"),
    path("<pk>/envoyer_confirm/", views.MsgDetailView.as_view(), name="envoyer_confirm"),
    path("<pk>/publier_confirm/", views.MsgDetailView.as_view(), name="publier_confirm"),
    path("<pk>/copier_confirm/", views.MsgDetailView.as_view(), name="copier_confirm"),
    path("<pk>/del_confirm/", views.MsgDetailView.as_view(), name="supprimer_confirm"),
    path("<msg_id>/envoyer/", views.msg_envoyer, name="envoyerok"),
    path("<msg_id>/publier/", views.msg_publier, name="publierok"),
    path("<msg_id>/copier/", views.msg_copier, name="copierok"),
    path("<msg_id>/del/", views.msg_delete, name="supprimerok"),
    path("<msg_id>/upd/", views.msg_update, name="msg_upd"),
    path("<msg_id>/preview/", views.preview_email, name="preview_email"),
    # path("<pk>/del/", views.MsgDeleteView.as_view(), name="supprimer"),
    path("<msg_id>/<msgdet_id>/viewdetail/", views.msgdet_consult, name="msgdet_consult"),
]

source/info/models.py
from filer.fields.image import FilerImageField
from ckeditor.fields import RichTextField

from django.db import models
from django.utils.translation import ugettext_lazy as _
# from accounts.models import GeoZip


class WebLink(models.Model):
    """
    Table liens utiles
    """
    DOMAINE_CHOICES = (
        (None, "-- Domaine --"),
        ("10-ACC", "Accompagnement"),
        ("20-BIO", "Bio - Local"),
        ("30-CPS", "Centre Pilote"),
        ("40-ENC", "Encadrement"),
        ("50-REC", "Recherche"),
        ("60-SPR", "Province"),
        ("65-WAL", "Wallonie"),
        ("70-AUT", "Autres liens"),
        ("90-CAT", "Catalogue"),
        ("94-DIA", "Diagnostique"),
        ("99-AUT", "Autre")     
    )
    CATEG_CHOICES = (
        (None, "-- Catégorie --"),
        ("outil", "Outils"),
        ("partenaire", "Partenaires"),
        ("autre", "Liens utiles"),
    )    
    code = models.CharField(max_length=20, unique=True)
    acronyme = models.CharField(_("Acronyme"), max_length=50)
    nom = models.CharField(max_length=255, unique=True)
    logo = FilerImageField(related_name="weblink_logo", on_delete=models.PROTECT, null=True, blank=True, verbose_name=_("Logo"))
    short_desc = RichTextField(verbose_name=_("Description"), blank=True, null=True)
    menucateg = models.CharField(_("Menu Categ"), max_length=20, choices=CATEG_CHOICES)
    domaine = models.CharField(_("Domaine"), max_length=6, choices=DOMAINE_CHOICES, blank=True, null=True)
    siteweb = models.URLField(_("Site web"), blank=True, null=True)
    contact = models.CharField(max_length=255, blank=True, null=True)
    tel = models.CharField(_('Tel'), max_length=15, blank=True, null=True,
        help_text="0 ou prefixe pays suivi de 8 à 9 chiffres")
    email = models.EmailField(_('Email'), blank=True, null=True)
    rue = models.CharField(_('Rue, nr de rue'), max_length=255, blank=True, null=True, help_text=_('Rue, nr rue'))
    codepostal = models.CharField(_('Code postal'), max_length=255, blank=True, null=True, help_text=_('CP et localisation'))
    # codepostal = models.ForeignKey(
    #     GeoZip, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('Code postal'))

    class Meta:
        verbose_name = _("Liens utile")
        ordering = ['acronyme']

    def get_logopath(self):
        logopath = self.logo.thumbnails['admin_directory_listing_icon']
        return logopath

    def get_logo(self):
        imgpath = self.get_logopath()
        imgtag = f'<img src="{imgpath}?reloadV44" alt="{self.acronyme}"/>'
        imghref = f'<a href="{self.siteweb}" target="_blank">{imgtag}</a>'
        return imghref

    def get_logo_large(self):
        # imgpath = self.get_logopath('admin_sidebar_preview')
        imgpath = self.logo.url
        imgtag = f'<img class="img-100 img-fluid" src="{imgpath}?reloadV44" alt="{self.acronyme}"/>'
        imghref = f'<a href="{self.siteweb}" target="_blank">{imgtag}</a>'
        return imghref

    def get_logo4email(self):
        filepath = self.get_logopath()
        pathlist = filepath.split('/')
        pathlen = len(pathlist)
        filename_full = pathlist[pathlen-1]
        imgtag = f'<img class="logo" src="cid:{filename_full}" alt="{self.acronyme}"/>'
        imghref = f'<a href="{self.siteweb}" target="_blank">{imgtag}</a>'
        return imghref

    def get_logo4email_preview(self):
        filepath = self.get_logopath()
        imgtag = f'<img class="logo" src="{filepath}" alt="{self.acronyme}"/>'
        imghref = f'<a href="{self.siteweb}" target="_blank">{imgtag}</a>'
        return imghref

    def get_title(self):
        title = f'<a href="{self.siteweb}" target="_blank">{self.acronyme}</a>'
        if self.acronyme != self.nom:
            title += f' {self.nom}'
        return title

    def __str__(self):
        return self.acronyme

source/info/views.py
# -*- coding: utf-8 -*-
"""
info.views
"""
import os
from datetime import timedelta
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView
from filer.models.filemodels import File
from info.models import WebLink
from msg.models import Msg
from config.settings import BASE_DIR
from accounts.formsearch import TxtSearchForm
from .formsearch import WebLinkSearchForm


def is_year(myvar):
    try:
        yyyy = int(myvar)
        if yyyy > 1990 and yyyy < 2050:
            return True
        else:
            return False
    except ValueError:
        return False


@login_required
def goaccess_list(request):
    path = os.path.join(BASE_DIR, 'templates', 'goaccess')
    year_list = [i for i in os.listdir(path)]
    year_list.sort()
    data = {}
    for year in year_list:
        if is_year(year):
            path_report = os.path.join(path, year)
            files = os.listdir(path_report)
            files.sort()
            report = {i[-12:][:7]: i for i in files if i.endswith(".html")}
            data[year] = report

    return render(
        request,
        'base_goaccess.html',
        {'title': 'Statistiques visites des CentresPilotes',
        'breadcrumb_display': 'Statistiques visites',
        'data': data
        }
    )


@login_required
def goaccess_report(request, month):
    report = request.GET.get('report', None)
    year = request.GET.get('year', None)
    if report is None:
        return render(request, '404.html')
    else:
        return render(
            request,
            'goaccess/{0}/{1}'.format(year, report)
        )


@login_required
def goaccess_report_year(request, year):
    return render(
        request,
        'goaccess/cpilote-{0}.html'.format(year)
    )


def accueil(request):
    cp_master_schema = File.objects.get(original_filename='cp-master-schema.png')
    dte6week = timezone.now()- timedelta(days=30)
    recent_msgs = Msg.objects.filter(msg_date__gte=dte6week).order_by('-msg_date')

    context = {
        'recent_msgs': recent_msgs,
        'cp_master_schema': cp_master_schema,
        }
    return render(request, 'info/accueil.html', context)


class WebLinkList(ListView):
    model = WebLink
    form = WebLinkSearchForm(None)
    template_name = "info/weblink_list.html"
    menucateg = 'autre'
    breadcrumb_display = ''
    url_name_list = ''
    totalrec = 0

    def __init__(self, menucateg='autre'):
        super().__init__()
        self.menucateg = menucateg
        if self.menucateg == 'outil':
            self.template_name = "info/outil_list.html"
        self.breadcrumb_display = ''.join([x[1] for x in self.model.CATEG_CHOICES if x[0]==self.menucateg])
        self.url_name_list = f'info:{self.menucateg}'

    def get_queryset(self):
        qs = self.model.objects.filter(menucateg=self.menucateg)
        self.totalrec = qs.count
        self.form = WebLinkSearchForm(self.request.GET)
        where = self.form.build_where()
        qs = qs.filter(where)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['breadcrumb_display'] = self.breadcrumb_display
        context['url_name_list'] = self.url_name_list
        context['totalrec'] = self.totalrec
        return context


class WebLinkDetail(DetailView):
    model = WebLink
    # template_name = 'modal/modal_info.html'


def weblink_detail(request):
    """
    Show detail
    """
    if request.method == "GET":
        wlid = request.GET.get("wlid")
    wl = WebLink.objects.get(pk=wlid)

    return render(
        request,
        "info/weblink_detail_modal.html",
        {"object": wl},
    )

source/info/templates/info/_accueil_txt.html
{% load thumbnail csstags %}
<h4 style="margin-top: 50px;">Origine</h4>
<div class="row">    
<div class="col-lg-9 col-md-12">
    <!-- Block text1 -->
    <div style="text-align: justify;">
        <p>La <a href="https://www.wallonie.be/fr" target="_blank">Wallonie</a> subsidie de nombreuses structures qui viennent en aide aux producteurs (agriculteurs et horticulteurs) pour des th&eacute;matiques tr&egrave;s diverses, allant de la logistique aux conseils techniques propres &agrave; un secteur particulier. Le sch&eacute;ma suivant illustre la diversit&eacute; des structures mises &agrave; votre disposition pour vous aider dans votre travail&nbsp;:</p>
        
        <picture>
            <source media="(max-width: 230px)" srcset="{{ cp_master_schema.thumbnails|lookup:'admin_sidebar_preview' }}">
            <source media="(max-width: 430px)" srcset="{% thumbnail cp_master_schema.file 300x225 crop %}">
            <source media="(max-width: 630px)" srcset="{% thumbnail cp_master_schema.file 400x300 crop %}">
            <source media="(max-width: 1050px)" srcset="{% thumbnail cp_master_schema.file 600x450 crop %}">
            <source media="(max-width: 1250px)" srcset="{% thumbnail cp_master_schema.file 800x600 crop %}">
            <img style="margin-bottom: 20px;" src="{% thumbnail cp_master_schema.file 1000x750 crop %}" alt="master_schema">
        </picture>
        <p>Le choix de la r&eacute;alisation ou non d&rsquo;un traitement, de la meilleure date de r&eacute;colte et plus g&eacute;n&eacute;ralement des strat&eacute;gies phytotechniques les plus ad&eacute;quates &agrave; mettre en place sont des d&eacute;cisions bien souvent difficiles &agrave; prendre pour les producteurs.</p>
        <p>Pour vous aider dans cette prise de d&eacute;cisions, seize structures sont agr&eacute;&eacute;es comme &laquo;&nbsp;centres pilotes&nbsp;&raquo; afin de vous fournir un service complet de d&eacute;veloppement et de vulgarisation. Parmi leurs missions, les centres pilotes ont d&eacute;velopp&eacute;, en collaboration avec de nombreux partenaires techniques, des avertissements <strong>neutres</strong> qui sont rassembl&eacute;s sur la pr&eacute;sente plateforme.</p>
        <p><strong>Un avertissement est</strong> un message bref, vous donnant des informations utiles dans la conduite de vos cultures, en fonction de la situation du moment (stade et &eacute;tat de la culture, vari&eacute;t&eacute;s, pression des organismes nuisibles, conditions et pr&eacute;visions m&eacute;t&eacute;orologiques, etc.). Il peut s&rsquo;agir d&rsquo;alertes &eacute;ventuellement assorties de conseils de traitements, de rappels, ou de suggestions. Ils constituent un ensemble couvrant r&eacute;guli&egrave;rement les p&eacute;riodes pertinentes. Les mod&egrave;les et les grilles de d&eacute;cision utilis&eacute;s pour la r&eacute;alisation des avertissements sont r&eacute;guli&egrave;rement valid&eacute;s par des observations et des essais r&eacute;alis&eacute;s par des experts r&eacute;guli&egrave;rement sur le terrain.</p>
        <p>Diffus&eacute;s tout au long de la saison, les avertissements mettent &agrave; votre disposition l&#39;avis concert&eacute; d&#39;experts publics notamment quant &agrave; l&#39;int&eacute;r&ecirc;t ou non de mener une intervention dans chacun des secteurs repr&eacute;sent&eacute;s par les centres pilotes et ce dans le cadre d&#39;une mise en pratique des principes de la lutte int&eacute;gr&eacute;e. Ces experts tentent donc de trouver le meilleur compromis pour assurer le contr&ocirc;le des maladies et des ravageurs dans les cultures.</p>
        <p>L&#39;avertissement est donc un v&eacute;ritable <strong>outil d&#39;aide &agrave; la d&eacute;cision</strong> pour les producteurs.</p>
        <p>Il a pour objectif de r&eacute;duire l&#39;usage des moyens de lutte, chimiques pour l&#39;essentiel, &agrave; ce qui est strictement n&eacute;cessaire en vous informant (par e-mail, sms, fax ou en consultant cette plateforme) de l&#39;importance du risque de pr&eacute;sence dans vos parcelles de ravageurs ou de maladies particuli&egrave;rement dommageables. Vous pourrez ensuite, apr&egrave;s avoir visit&eacute; attentivement vos propres parcelles, d&eacute;cider d&#39;intervenir ou non en connaissance d&#39;effet et de cause.</p>
        <p>Ils assurent ainsi la protection de vos cultures sans d&eacute;penses excessives d&#39;intrants.</p>
        <p>Pour les grandes cultures, les avertissements donnent une situation g&eacute;n&eacute;rale sur l&#39;ensemble de la zone de production. L&#39;&eacute;tendue de cette zone est telle que les observations sont r&eacute;alis&eacute;es par un r&eacute;seau d&#39;observateurs form&eacute;s sp&eacute;cialement &agrave; cet effet.</p>
        <p>Pour les cultures plus sp&eacute;cifiques telles que les l&eacute;gumes industriels, un suivi personnalis&eacute; des parcelles du producteur est n&eacute;cessaire. Contrairement aux grandes cultures, les avertissements reprennent dans ce cas la situation de chaque parcelle suivie, avec avis de traitement si n&eacute;cessaire.</p>
    </div>
</div>
</div>

<div class="row">
<div class="col-lg-9 col-md-12">
    <p><strong>Avertissements actuellement disponibles:</strong></p>
    <table align="center" class="table table-striped" height="696" style="width: 100%;">
        
        <thead>
            <tr>
                <th scope="col">Culture</th>
                <th scope="col">Avertissement</th>
                <th scope="col">Structure</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Arboriculture fruiti&egrave;re</td>
                <td>G&eacute;n&eacute;raux (maladies et ravageurs)</td>
                <td>Profruit (PCFruit)</td>
            </tr>
            <tr>
                <td>Arboriculture fruiti&egrave;re</td>
                <td>Techniques (conventionnel)</td>
                <td>CEF</td>
            </tr>
            <tr>
                <td>Arboriculture fruiti&egrave;re</td>
                <td>Production int&eacute;gr&eacute;e</td>
                <td>GAWI</td>
            </tr>
            <tr>
                <td>Betterave</td>
                <td>Maladies, ravageurs</td>
                <td>IRBAB</td>
            </tr>
            <tr>
                <td>Carotte industrielle</td>
                <td>Maladies, ravageurs</td>
                <td>CPL V&eacute;g&eacute;mar</td>
            </tr>
            <tr>
                <td>C&eacute;r&eacute;ales</td>
                <td>Maladies, ravageurs et phytotechnie</td>
                <td>CEPICOP</td>
            </tr>
            <tr>
                <td>Chicor&eacute;e</td>
                <td>Maladies, ravageurs</td>
                <td>IRBAB</td>
            </tr>
            <tr>
                <td>Chou de Bruxelles</td>
                <td>Ravageurs</td>
                <td>CPL V&eacute;g&eacute;mar</td>
            </tr>
            <tr>
                <td>F&egrave;ve des marais</td>
                <td>Ravageurs (bruche et pucerons)</td>
                <td>CPL V&eacute;g&eacute;mar</td>
            </tr>
            <tr>
                <td>Floriculture</td>
                <td>Maladies (dont rouille du Chrysant&egrave;me), ravageurs</td>
                <td>CEHW</td>
            </tr>
            <tr>
                <td>Fraises et petit fruits</td>
                <td>Maladies, ravageurs</td>
                <td>GFW</td>
            </tr>
            <tr>
                <td>Ma&iuml;s</td>
                <td>Pucerons</td>
                <td>CPM</td>
            </tr>
            <tr>
                <td>Ma&iuml;s fourrage</td>
                <td>Date de r&eacute;colte</td>
                <td>CPL V&eacute;g&eacute;mar</td>
            </tr>
            <tr>
                <td>Ma&iuml;s grain</td>
                <td>Date de r&eacute;colte</td>
                <td>CIPF</td>
            </tr>
            <tr>
                <td>Mara&icirc;chage</td>
                <td>Maladies, ravageurs</td>
                <td>CIM</td>
            </tr>
            <tr>
                <td>Ol&eacute;o-prot&eacute;agineux</td>
                <td>Ravageurs</td>
                <td>CEPICOP</td>
            </tr>
            <tr>
                <td>Orges brassicoles</td>
                <td>Maladies, ravageurs et phytotechnie</td>
                <td>CEPICOP</td>
            </tr>
            <tr>
                <td>P&eacute;pini&egrave;res ornementales</td>
                <td>Maladies, ravageurs</td>
                <td>CEHW</td>
            </tr>
            <tr>
                <td>Pommes de terre</td>
                <td>Mildiou</td>
                <td>CARAH</td>
            </tr>
            <tr>
                <td>Pommes de terre</td>
                <td>Pucerons en culture de plants</td>
                <td>CRA-W</td>
            </tr>
            <tr>
                <td>Pommes de terre</td>
                <td>Pucerons en pomme de terre de consommation</td>
                <td>CARAH</td>
            </tr>
            <tr>
                <td>Sapin de No&euml;l</td>
                <td>Puceron lanig&egrave;re du sapin</td>
                <td>UAP</td>
            </tr>
        </tbody>
    </table>
</div>
</div>

source/info/templates/info/accueil.html
{% extends 'base.html' %}
{% load static csstags thumbnail sekizai_tags %}

{% block title %}Accueil{% endblock %}

{% block extrastyle %}
<link rel="stylesheet" href="{% static 'css/dist/flickity.css' %}" media="screen">
{% endblock extrastyle %}


{% block content %}
<h2>Bienvenue sur la plateforme des productions végétales de Wallonie</h2>
<br><br>
<div class="row"> 
    <div class="col-lg-9 col-md-12">
        <div class="grey-box">
        <p>Les avertissements sont un <strong>service gratuit</strong> proposé au monde agricole.</p>
        <p>Pour les recevoir par email dès leur publication, il faut <a href="{% url 'signup' %}" class="btn btn-outline-secondary me-2">s'inscrire</a> et cocher les listes d'envois qui vous intéressent.</p>
        <p>Selon les périodes pertinentes (risques ravageurs), les avertissements Céréales et/ou Colza sont envoyés <strong>tous les mardi</strong> en début d’après-midi.</p>
        </div>
    </div>
</div>


{% include "info/_accueil_txt.html" %}

{% endblock content %}

{% block js %}
    {{block.super}}
    <script src="{% static 'js/flickity.pkgd.min.js' %}"></script>
{% endblock js %}

source/info/templates/info/outil_list.html
{% extends 'base.html' %}
{% load static csstags menu_tags %}

{% block title %}Liens utiles{% endblock %}


{% block breadcrumb %}
{% show_breadcrumb 1 "menu/_breadcrumb_direct.html" 0 %}
{% endblock breadcrumb %}


{% block content %}
<div class="flex-container">
    {% include 'forms/listsearch_form.html' %}
    {% include 'forms/listsearch_counter.html' %}
</div>

{% for wl in object_list %}

    {% if wl.code != 'cpcollect' %}
    <div class="row">
        <div class="col-12">
                <hr class="hr-cp"/>
                <a href="{{wl.siteweb}}" target="_blank">
                    <img class="img-left img-fluid img-200" src="{{ wl.logo.url }}" alt="{{ wl.get_title }}">
                </a>
                <div class="text-justify container-text">
                    <a href="{{wl.siteweb}}" target="_blank" class="btn btn-main2 mb-2">{{wl.acronyme}}</a>
                    {{ wl.short_desc|safe }}
                </div>
        </div>
    </div>
    {% else %}
        
        <div class="row">
            <div class="col-12">
                    <hr class="hr-cp"/>
                    <a href="{{wl.siteweb}}" target="_blank">
                        <img class="img-left img-fluid img-200" src="{{ wl.logo.url }}" alt="{{ wl.get_title }}">
                    </a>
                    <div class="text-justify container-text">
                        <a href="{{wl.siteweb}}" target="_blank" class="btn btn-main2 mb-2">{{wl.acronyme}}</a>
                        {{ wl.short_desc|safe }}
                    </div>
            </div>
        </div>
        
    {% endif %}

{% endfor %}


{% endblock content %}

{% block js %}
{{ block.super }}
<script>
    function submitForm() {
        $("#listsearch_form").submit();
    }

    $(document).ready(function () {
        $("#id_domaine").on('change', submitForm);
    });
</script>
{% endblock js %}

source/info/templates/info/weblink_detail_modal.html
<div class="modal-dialog">
  <div class="modal-content">

    <div class="modal-header">
      <h4 class="modal-title">{{ object.get_title|safe }}</h4>
      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>          
    </div>

    <div class="modal-body">
      <!-- bloc text -->
      <div class="row">
        <div class="col-sm-12">
          <img class="img-left img-fluid img-200" src="{{ object.logo.url }}" alt="{{ object.acronyme }}">
          <div class="container-text">{{ object.short_desc|safe }}</div>
        </div>
      </div>

      <!-- bloc contact -->
      <div class="row">
        <div class="col-sm-12">      
          <div class="flex-container-start"><!-- adresse -->
            <p class="me-2"><i class="far fa-envelope"></i></p>
            <div class="address">
                <div>
                    <p>{{object.rue|default_if_none:""}}</p>
                    <p>{{object.codepostal|default_if_none:""}}</p>
                </div>
            </div>
          </div>

          <div><!-- email & phone -->
            {% if object.email %}
              <p><i class="fas fa-at me-2"></i><a href="mailto:{{object.email}}">{{object.email}}</a></p>
            {% endif %}
            {% if object.tel %}
                <p><i class="fas fa-phone-alt me-2"></i>{{object.tel}}</p>
            {% endif %}
          </div>
        </div>
      </div>

    </div><!-- end modal-body -->

    <div class="modal-footer">
      <button type="button" class="btn btn-main2" data-bs-dismiss="modal">Fermer</button>
    </div>

  </div>
</div>

source/info/templates/info/weblink_list.html
{% extends 'base.html' %}
{% load static csstags menu_tags %}

{% block title %}Liens utiles{% endblock %}

{% block breadcrumb %}
{% show_breadcrumb 1 "menu/_breadcrumb_direct.html" 0 %}
{% endblock breadcrumb %}

{% block content %}
<div class="flex-container">
    {% include 'forms/listsearch_form.html' %}
    {% include 'forms/listsearch_counter.html' %}
</div>

<div class="flex-container">
    {% for wl in object_list %}
    <div class="container-box-white">      
        <hr class="hr-cp"/>
        <a href="#" id={{wl.id}} class="wl-detail">
            <h4>{{wl.acronyme}}<i class="ms-2 fas fa-info-circle"></i></h4>
        </a>
        <a href="{{wl.siteweb}}" target="_blank">
            <img class="img-fluid img-200" src={{wl.logo.url}} alt={{wl.get_title}}>
        </a>
    </div>  
    {% endfor %}
</div>

<div class="modal" id="WebLinkDetail"></div>

{% endblock content %}

{% block js %}
{{ block.super }}
<script>
    function submitForm() {
        $("#listsearch_form").submit();
    }

    function getID() {
        var wlid = $(this).attr('id');
        $.ajax({
            url: '{% url "info:weblink_detail" %}',
            data: {
                'wlid': wlid
            },
            success: function (data) {
                $("#WebLinkDetail").html(data);
                $("#WebLinkDetail").modal('show');
            }
        });
    }

    $(document).ready(function () {
        $("#id_domaine").on('change', submitForm);
        $(".wl-detail").on('click', getID); 
    }); 
</script>
{% endblock js %}