source/agenda/urls.py
# encoding:utf-8
'''
Created on 07/06/2021
@author: p.houben
'''
from django.urls import path
# from django.views.i18n import JavaScriptCatalog
from agenda import views

app_name = "agenda"

urlpatterns = [
    path('', views.home, name='event_home'),
    path('<p_year>/<p_month>/', views.event_list, name='event_list'),
    path('<pk>', views.EventDetailView.as_view(), name='event_detail'),
    path("<pk>/copy", views.event_copy, name="event_copy"),
    path('<pk>/upd', views.EventUpdateView.as_view(), name='event_update'),
    path('<pk>/del', views.EventDeleteView.as_view(), name='event_delete'),
    path('add/', views.EventCreateView.as_view(), name='event_create'),
    # path('jsi18n/', JavaScriptCatalog.as_view(), name='js_catalog'),
]

source/config/urls.py
# djauth/urls.py
from . import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from accounts import ajax_call
from msg import ajax_call as msg_ajax_call
from django.conf.urls import url


urlpatterns = [
    path('chapeau/', admin.site.urls),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('agenda/', include('agenda.urls'), name='agenda'),
    path('accueil/', include('info.urls'), name='info'),
    path('odk/', include('odk.urls'), name='odk'),
    # path('culture/', include('cult.urls'), name='cult'),
    url(r'^filer/', include('filer.urls')),
    path('', include('cms.urls'), name='cpcms'), # HBP attention BASE_URL du CMS
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = urlpatterns + [
    path('ajax/ddl_zip', ajax_call.ddl_zip, name='ajax_ddl_zip'),
    path('ajax/ddl_contact', ajax_call.ddl_contact, name='ajax_ddl_contact'),
    path('ajax/inscription/upd', ajax_call.inscription_update, name='inscription_update'),
    path('ajax/inscription_block/create', ajax_call.inscription_block_create, name='inscription_block_create'),
    path('ajax/msgdet/del', msg_ajax_call.msgdet_delete, name='msgdet_delete'),
]


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

source/info/urls.py
# encoding:utf-8
'''
Created on 13/04/2020
@author: p.houben
'''
from django.urls import path
from .views import (
    WebLinkList, WebLinkDetail, weblink_detail,
    goaccess_list, accueil, goaccess_report, goaccess_report_year
)

app_name = "info"

urlpatterns = [
    path('', accueil, name='accueil'),
    path('autres/', WebLinkList.as_view(menucateg='autre'), name='autre'),
    path('partenaires/', WebLinkList.as_view(menucateg='partenaire'), name='partenaire'),
    path('outils/', WebLinkList.as_view(menucateg='outil'), name='outil'),
    # ne pas changer ci-dessous, c'est une popup avec appel ajax!
    path('detail/', weblink_detail, name='weblink_detail'), 
    path('statistiques/', goaccess_list, name='cpilote_stat'),
    path('statistiques/mensuelle/<month>', goaccess_report, name='goaccess_report'),
    path('statistiques/annuelle/<year>', goaccess_report_year, name='goaccess_report_year'),
]

source/msg/urls.py
# -*- coding: utf-8 -*-
"""
msg.urls description

.. todo:: ajouter la navigation dans les centres pilotes
.. todo:: ajouter la navigation dans les cultures
"""
# from django.conf.urls import url
from django.urls import path
from django.conf import settings

from . import views

__author__ = "jph"
__email__ = "jph@openjph.be"
__copyright__ = "Copyright 2016, Jean Pierre Huart"
__license__ = "GPLv3"
__date__ = "2016-12-01"
__version__ = "1.1"
__status__ = "Development"

app_name = "msg"
# pour pouvoir utiliser msg:rech_mult dans les url

urlpatterns = [
    path("", views.MsgListView.as_view(), name="msg_list"),
    # path("oleagineux?listeenvoi=15", views.MsgListView.as_view(), name="msg_list_oleo"),
    path("rechmult/", views.MsgListView.as_view(), name="rechmult"),
    path("new/", views.msg_new, name="new"),
    path("<pk>", views.MsgDetailView.as_view(), name="msg_consult"),
    path("<pk>/envoyer_confirm/", views.MsgDetailView.as_view(), name="envoyer_confirm"),
    path("<pk>/publier_confirm/", views.MsgDetailView.as_view(), name="publier_confirm"),
    path("<pk>/copier_confirm/", views.MsgDetailView.as_view(), name="copier_confirm"),
    path("<pk>/del_confirm/", views.MsgDetailView.as_view(), name="supprimer_confirm"),
    path("<msg_id>/envoyer/", views.msg_envoyer, name="envoyerok"),
    path("<msg_id>/publier/", views.msg_publier, name="publierok"),
    path("<msg_id>/copier/", views.msg_copier, name="copierok"),
    path("<msg_id>/del/", views.msg_delete, name="supprimerok"),
    path("<msg_id>/upd/", views.msg_update, name="msg_upd"),
    path("<msg_id>/preview/", views.preview_email, name="preview_email"),
    # path("<pk>/del/", views.MsgDeleteView.as_view(), name="supprimer"),
    path("<msg_id>/<msgdet_id>/viewdetail/", views.msgdet_consult, name="msgdet_consult"),
]

source/templates/403_csrf.html
{% extends 'base.html' %}

{% block title %}Forbidden (403){% endblock title %}

{% block content %}
<h1>Forbidden (403)</h1>
<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

source/templates/_django_pagecounter.html
{% load csstags %}
<div class="flex-container-start">
	<span class="page-text">Ligne</span>
	<span class="page-counter">{% frompageline page_obj.number view.paginate_by page_obj.paginator.count %}</span>
	<span class="page-text">à</span>
	<span class="page-counter">{% topageline page_obj.number view.paginate_by page_obj.paginator.count %}</span>
	<span class="page-text">sur</span>
	<span class="page-counter">{{ page_obj.paginator.count }}</span>
</div>

source/templates/_django_pager.html
{% load csstags %}
{% comment %}
https://getbootstrap.com/docs/4.1/components/pagination/
{% endcomment %}



{% if is_paginated %}

  <ul class="pagination">

	{% if page_obj.has_previous %}

	  <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">&laquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a href="#" class="page-link">&laquo;</a></li>
    {% endif %}

    {% for i in page_obj.paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active"><a href="#" class="page-link">{{ i }}<span class="sr-only">(current)</span></a></li>
      {% else %}
        <li class="page-item"><a class="page-link" href="?{% url_replace page=i %}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}


	{% if page_obj.has_next %}
	  <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">&raquo;</a></li>
    {% else %}
      <li class="page-item disabled"><a href="#" class="page-link">&raquo;</a></li>
    {% endif %}
  </ul>

{% endif %}

source/templates/_footer.html
{% load static settings_tags %}

<footer class="page-footer mt-auto py-3 font-small">
    <div class="d-flex justify-content-between">
        
        <a target="_blank" rel="noopener noreferrer" href="https://spw.wallonie.be/">
            <img class="logo" height="40" width="118" 
                alt="wallonie" src="{% static 'img/logo/spw172.png' %}"
                title="Service Public de Wallonie">
        </a>

        <div>
            <ul style="list-style: none; text-align: left;">
                <li>&copy; <a href="http://www.cra.wallonie.be" target="_blank">CRA-W</a> 2021</li>
                <li>Nous <a href="mailto:centrespilotes@cra.wallonie.be">contacter</a></li>
            </ul>
        </div>
        
        <div></div>
        <a id="GoToTop" class="scroll-to-top rounded" href="#">
            <i class="fas fa-angle-up"></i>
        </a>
    </div>

</footer>

source/templates/_messages.html
<!-- https://simpleisbetterthancomplex.com/tips/2016/09/06/django-tip-14-messages-framework.html -->

{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    {{ message }}
  </div>
{% endfor %}

source/templates/base.html
{% load static settings_tags i18n sekizai_tags cms_tags menu_tags %}
<!DOCTYPE html>
<html lang="fr">
<head>

<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

<meta name="google" content="notranslate">
<meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
<meta name="description" content="A framework for launching new Django projects quickly.">
<meta name="author" content="Patrick Houben">

<link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

<title>{% block title %}CentresPilotes{% endblock title %}</title>

{% block css %}
	<link rel="stylesheet" href="{% static 'css/dist/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/dist/main.css' %}?reload=V47">
	<link rel="stylesheet" href="{% static 'fontawesome-free-5.12.1-web/all.min.css' %}">
{% endblock css %}

{% block extrastyle %}
{% endblock extrastyle %}

{% render_block "css" %}
</head>

<body id="page-top">
	{% cms_toolbar %}

	<nav class="navbar navbar-expand-md navbar-light bg-light">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#masterMenu" aria-controls="navbarNavDarkDropdown" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="masterMenu">
			<ul class="nav nav-tabs">
				{% block mainmenu %}
				<li class='child nav-item'><a class="nav-link" href="/">Accueil</a></li>
				<li class='child nav-item'><a class="nav-link" href="/cp/">Centres pilotes</a></li>
				<li class='child nav-item'><a class="nav-link" href="{% url 'msg:msg_list' %}?annee={% now 'Y'%}">Avertissements</a></li>
				<li class='child nav-item'><a class="nav-link" href="{% url 'agenda:event_home' %}">Agenda</a></li>
				<li class='child nav-item'><a class="nav-link" href="{% url 'info:outil' %}">Outils</a></li>
				<li class='child nav-item'><a class="nav-link" href="{% url 'info:partenaire' %}">Partenaires</a></li>
				<li class='child nav-item'><a class="nav-link" href="{% url 'info:autre' %}">Liens utiles</a></li>
				{% endblock mainmenu %}
			</ul>

			{% if user.is_authenticated %}
			<ul class="nav navbar-nav ms-auto">
				<li class="nav-item dropdown child">
					<a class="nav-link dropdown-toggle" href="#" id="accounts_menu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
						{{ user.email }}
					</a>
					<ul class="dropdown-menu dropdown" aria-labelledby="accounts_menu">
						<li><a class="dropdown-item" href="{% url 'profile_detail' user.id %}">{% trans "Mon compte" %}</a></li>
						<li><a class="dropdown-item" href="{% url 'inscription_1_user' user.id %}">{% trans "Mes inscriptions" %}</a></li>

						{% if user.is_manager %}
							<li><a class="dropdown-item" href="{% url 'cp_detail' user.manage_cp.id %}">{% trans "Mon centre pilote" %}</a></li>
							<li><a class="dropdown-item" href="{% url 'listeenvoi_list' %}">{% trans "Liste envoi " %}{{ user.manage_cp.acronyme }}</a></li>
							<li><a class="dropdown-item" href="{% url 'profile_create' %}">{% trans "Ajouter utilisateur" %}</a></li>
							<li><a class="dropdown-item" href="{% url 'info:cpilote_stat' %}">{% trans "Statistiques visites" %}</a></li>
						{% endif %}

						{% if user.is_odk_admin %}
							<li><a class="dropdown-item" href="{% url 'odk:xform_list' %}">{% trans "ODK formulaires disponibles" %}</a></li>
							<li><a class="dropdown-item" href="{% url 'odk:xformsubmit_list' %}">{% trans "ODK formulaires soumis" %}</a></li>
						{% endif %}

						<li><a class="dropdown-item" href="{% url 'logout' %}">{% trans "Déconnexion" %}</a></li>
					</ul>
				</li>
			</ul>
			{% else %}
			<ul class="nav navbar-nav ms-auto">
				<li class="nav-item">
				<form>
					<a href="{% url 'login' %}" class="nav-link">{% trans "Se connecter" %}</a>
				</form>
				</li>
			</ul>
			{% endif %}
			</div>
		</div>
	</nav>

	{% block cpmenu %}
	{% endblock cpmenu %}

	<div class="wrapper">
		{% block sidebar %}
			{% include 'menu/_base_sidebar.html' %}
		{% endblock sidebar %}

		<div id="content" class="content">

			{% block breadcrumb %}
			{% show_breadcrumb 0 "menu/_breadcrumb.html" 0 %}
			{% endblock breadcrumb %}

			<div class="banner-content">
			{% block banner %}
			{% endblock banner %}
			</div>
			
			{% block main_content %}
			<div class="container">
				{% include '_messages.html' %}

				{% block content_title %}<h2>{{ title }}</h2>{% endblock content_title %}

				{% block content %}
					{% with 720 as width and 480 as height %}
						{% placeholder "content" %}
					{% endwith %}
				{% endblock content %}
			</div>
			{% endblock main_content %}

		</div>

	</div>

	{% include '_footer.html' %}

	{% block js %}
		<script>
			var base_url = "{% settings_value 'BASE_URL' %}";
		</script>
		<script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/cpmain.js' %}?reload=V21"></script>
	{% endblock js %}
	
	{% render_block "js" %}
</body>
</html>

source/templates/base_goaccess.html
{% extends 'base.html' %}
{% load csstags menu_tags i18n %}

{% block title %}{{ title }}{% endblock title %}

{% block breadcrumb %}
{% show_breadcrumb 1 "menu/_breadcrumb_direct.html" 0 %}
{% endblock breadcrumb %}

{% block content %}
{% for year, year_items in data.items %}
    <h3><a href="{% url 'info:goaccess_report_year' year %}" target="_blank">{% trans "Année" %} {{ year }}</a></h3>
    <ul>
        {% for month, report in year_items.items %}
            <li class="my-3">
                <a href="{% url 'info:goaccess_report' month %}?year={{ year }}&report={{ report }}" target="_blank">{% trans "Mois" %} {{ month }}</a>
            </li>
        {% endfor %}
    </ul>
{% endfor %}

{% endblock content %}